course_name: CS1511
roles:
  - tutor:
    duration: 3 # number of hours for tutorials
    offset: 0
  - assist:
    duration: 2
    offset: 1
bad_pair_limits: 5


# role(tute).
# requirement(tute,1).
# duration(tute,3).
# offset(tute,0).

# role(asst).
# requirement(asst,1).
# duration(asst,2).
# offset(asst,1).

# badPairsLimit(5). % how many slots do we accept with a pair of inexperienced teachers?

# desireLevel(dislike). desireLevel(possible). desireLevel(preferred).
# lessDesired(dislike,possible). lessDesired(dislike,preferred). lessDesired(possible,preferred).
# upperSatisfactionBound(dislike,0). % no task should be disliked
# upperSatisfactionBound(possible,0). % no more than 1 task should be "possible"
